project:
  type: website
  output-dir: docs #comment bagian ini sebelum melakukan preview 
  
website:
  title: "Daffa Daniel Rivaldi"
  site-url: https://daffadanielr.github.io/


  # open-graph: true

  navbar:
    background: primary
    search: true
    left:
      - text: "About"
        href: about.qmd 

      - text: "Portofolio"
        href: portofolio.qmd

  sidebar:
    - title: "Portofolio"
      style: "floating"
      background: light
      contents:
        - text: Portofolio
          href: portofolio.qmd 

        - text: "Project 2: Mentoring 3"
          href: posts\project-2\index.qmd


page-footer:
    right: "This blog is built with [Quarto](https://quarto.org/)."
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  eval: false
  freeze: true

publish:
  - gh-pages: true