project:
  type: website
  output-dir: docs
  
website:
  title: "Daffa Daniel Rivaldi"

  navbar:
    background: primary
    search: true
    left:
      - text: "About"
        href: index.qmd 
      - text: "Portofolio"
        href: portofolio.qmd
      - text: "CV"
        href: cv.qmd
      - text: "About"
        href: about.qmd


  sidebar:
    - title: "Portofolio"
      style: "floating"
      background: light
      contents:
        - text: portofolio
          href: portofolio.qmd 
        - project 1.qmd
        - hello.qmd
        - text: "Mentoring 3"
          href: notebooks/DaffaDanielR_Mentoring_3_Introduction_to_Machine_Learning.ipynb

  
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: true

publish:
  - gh-pages: true